//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input System/Player Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Controls"",
    ""maps"": [
        {
            ""name"": ""BasicAction"",
            ""id"": ""5444ec47-6749-4336-99ac-29534346ffa1"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""2022de74-01f2-408d-9a56-810b042e19b8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""75fdb3ef-2697-45ed-9159-a1c5279fa76e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BuidingMode"",
                    ""type"": ""Button"",
                    ""id"": ""192dbd70-c23a-47d4-be4a-c5cea0ab92a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Buiding"",
                    ""type"": ""Button"",
                    ""id"": ""90ea0459-4247-4033-9ff4-daec154bab5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateBulid"",
                    ""type"": ""Button"",
                    ""id"": ""4d22968d-f0ad-491c-a6e6-e1d6f29e376e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b8647e2c-0b59-462b-8e19-4bd088d95554"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e3ca137c-20ac-4ac7-9642-bbbd4e5414da"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""02aba5c7-db0f-44a3-8e67-183c6ec6a100"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""04d93006-2fde-4e75-a38d-ab562ed44a41"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""46fe3d10-cb76-49a9-aeb4-a0df25a33957"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""044a9dc5-387c-493d-94be-f6b43c0277d9"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29617d57-dbb4-491f-b327-9f5721c4c6a0"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b869f076-c9f9-49e3-a215-b3fd028a1391"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuidingMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07b803ad-691d-47b8-a11f-c1ab04d548bf"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Buiding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d351c1d-bd48-4324-82e8-9ffe58b346c0"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateBulid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BasicAction
        m_BasicAction = asset.FindActionMap("BasicAction", throwIfNotFound: true);
        m_BasicAction_Movement = m_BasicAction.FindAction("Movement", throwIfNotFound: true);
        m_BasicAction_Rotate = m_BasicAction.FindAction("Rotate", throwIfNotFound: true);
        m_BasicAction_BuidingMode = m_BasicAction.FindAction("BuidingMode", throwIfNotFound: true);
        m_BasicAction_Buiding = m_BasicAction.FindAction("Buiding", throwIfNotFound: true);
        m_BasicAction_RotateBulid = m_BasicAction.FindAction("RotateBulid", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BasicAction
    private readonly InputActionMap m_BasicAction;
    private List<IBasicActionActions> m_BasicActionActionsCallbackInterfaces = new List<IBasicActionActions>();
    private readonly InputAction m_BasicAction_Movement;
    private readonly InputAction m_BasicAction_Rotate;
    private readonly InputAction m_BasicAction_BuidingMode;
    private readonly InputAction m_BasicAction_Buiding;
    private readonly InputAction m_BasicAction_RotateBulid;
    public struct BasicActionActions
    {
        private @PlayerControls m_Wrapper;
        public BasicActionActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_BasicAction_Movement;
        public InputAction @Rotate => m_Wrapper.m_BasicAction_Rotate;
        public InputAction @BuidingMode => m_Wrapper.m_BasicAction_BuidingMode;
        public InputAction @Buiding => m_Wrapper.m_BasicAction_Buiding;
        public InputAction @RotateBulid => m_Wrapper.m_BasicAction_RotateBulid;
        public InputActionMap Get() { return m_Wrapper.m_BasicAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BasicActionActions set) { return set.Get(); }
        public void AddCallbacks(IBasicActionActions instance)
        {
            if (instance == null || m_Wrapper.m_BasicActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BasicActionActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @BuidingMode.started += instance.OnBuidingMode;
            @BuidingMode.performed += instance.OnBuidingMode;
            @BuidingMode.canceled += instance.OnBuidingMode;
            @Buiding.started += instance.OnBuiding;
            @Buiding.performed += instance.OnBuiding;
            @Buiding.canceled += instance.OnBuiding;
            @RotateBulid.started += instance.OnRotateBulid;
            @RotateBulid.performed += instance.OnRotateBulid;
            @RotateBulid.canceled += instance.OnRotateBulid;
        }

        private void UnregisterCallbacks(IBasicActionActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @BuidingMode.started -= instance.OnBuidingMode;
            @BuidingMode.performed -= instance.OnBuidingMode;
            @BuidingMode.canceled -= instance.OnBuidingMode;
            @Buiding.started -= instance.OnBuiding;
            @Buiding.performed -= instance.OnBuiding;
            @Buiding.canceled -= instance.OnBuiding;
            @RotateBulid.started -= instance.OnRotateBulid;
            @RotateBulid.performed -= instance.OnRotateBulid;
            @RotateBulid.canceled -= instance.OnRotateBulid;
        }

        public void RemoveCallbacks(IBasicActionActions instance)
        {
            if (m_Wrapper.m_BasicActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBasicActionActions instance)
        {
            foreach (var item in m_Wrapper.m_BasicActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BasicActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BasicActionActions @BasicAction => new BasicActionActions(this);
    public interface IBasicActionActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnBuidingMode(InputAction.CallbackContext context);
        void OnBuiding(InputAction.CallbackContext context);
        void OnRotateBulid(InputAction.CallbackContext context);
    }
}
